---
dockge_enabled: false
dockge_available_externally: false

# directories
dockge_data_directory: "{{ docker_home }}/dockge/config"
dockge_stacks_directory: "{{ docker_home }}/dockge/stacks"

# network
dockge_port: "5001"
dockge_hostname: "dockge"

# docker
dockge_container_name: "dockge"
dockge_image_name: "louislam/dockge"
dockge_image_version: "latest"

# specs
dockge_memory: 1g
