---
- name: Install some packages
  ansible.builtin.apt:
    name: "{{ ansible_nas_extra_packages }}"
    state: present
  register: result
  until: result is succeeded


- name: configure fail2ban for ssh
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.local
    content: "{{ f2b_jail_local }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart fail2ban

- name: enable fail2ban service on boot
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: started

# simple shell script to display fail2ban-client status info; usage:

#   f2bst

#   f2bst sshd

- name: Configure f2bst
  ansible.builtin.copy:
    dest: /usr/local/bin/f2bst
    content: |

      #!/bin/sh

      fail2ban-client status $*

    owner: root
    group: root
    mode: 0750

- name: Make sure that the neofetch config folder is created
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/neofetch"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "0755"

- name: Deploy the neofetch configuration file in place
  ansible.builtin.copy:
    src: config.conf
    dest: "{{ ansible_env.HOME }}/.config/neofetch/config.conf"
  
- name: Install LazyDocker
  ansible.builtin.shell:
    cmd: curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
  args:
    creates: /usr/local/bin/lazydocker
  environment:
    DIR: /usr/local/bin

- name: "Permission share directories"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: ansible-nas
    group: ansible-nas
    mode: "u=rwX,g=rwX,o=rX"
    recurse: false
  loop: "{{ samba_shares }}"
