---
lidarr_enabled: false
lidarr_available_externally: false

# directories
lidarr_data_directory: "{{ docker_home }}/lidarr/config"
lidarr_music_directory: "{{ music_root }}"
lidarr_downloads_directory: "{{ downloads_root }}"

# uid/gid
lidarr_user_id: "{{ uid }}"
lidarr_group_id: "{{ gid }}"

# network
lidarr_port: "8686"
lidarr_hostname: "lidarr"
lidarr__ports: 
  - "{{ lidarr_port }}:{{ container_lidarr_port }}"

# docker
lidarr_container_name: "lidarr"
lidarr_image_name: "linuxserver/lidarr"
lidarr_image_version: "latest"

# specs
lidarr_memory: 1g
