---
roles:
  - name: geerlingguy.docker
    version: 7.0.2

  - name: geerlingguy.docker_arm
    version: 5.0.0

  - name: bertvv.samba
    version: v2.7.1

  - name: geerlingguy.nfs
    version: 2.0.0

  - name: geerlingguy.firewall
    version: 2.5.1

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general
