---
ombi_enabled: false
ombi_available_externally: false

# directories
ombi_config_directory: "{{ docker_home }}/ombi/config"

# network
ombi_port: "3579"
ombi_hostname: "ombi"
ombi__ports: 
  - "{{ ombi_port }}:{{ container_ombi_port }}"

# docker
ombi_container_name: "ombi"
ombi_image_name: "linuxserver/ombi"
ombi_image_version: "latest"
ombi_user_id: "{{ uid }}"
ombi_group_id: "{{ gid }}"

# specs
ombi_memory: 1g
