---
ubooquity_enabled: false
ubooquity_available_externally: false

# uid / gid
ubooquity_user_id: "{{ uid }}"
ubooquity_group_id: "{{ gid }}"

# Directories
ubooquity_data_directory: "{{ docker_home }}/ubooquity"

# Networking
ubooquity_port_webui: "2202"
ubooquity_port_admin: "2203"
ubooquity_hostname: ubooquity
ubooquity__ports: 
  - "{{ ubooquity_port_webui }}:{{ container_ubooquity_port_webui }}"
  - "{{ ubooquity_port_admin }}:{{ container_ubooquity_port_admin }}"

# Container
ubooquity_memory: 1g
ubooquity_container_name: "ubooquity"
ubooquity_image_name: "linuxserver/ubooquity"
ubooquity_image_version: "latest"
