---
- name: Create ansible-nas group
  ansible.builtin.group:
    name: ansible-nas
    state: present

- name: Create ansible-nas user
  ansible.builtin.user:
    name: ansible-nas
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: ansible-nas
    shell: /usr/sbin/nologin
  register: user_info

- name: "Set 'uid' and 'gid'"
  ansible.builtin.set_fact:
    uid: "{{ user_info.uid }}"
    gid: "{{ user_info.group }}"
