---
# Extra packages to install
ansible_nas_extra_packages:
  - docker-ctop
  - docker-compose
  - htop
  - curl
  - ripgrep
  - lsof
  - rsync
  - iotop
  - neofetch
  - lolcat
  - fzf
  - zoxide
  - bat
  - exa
  - tmux
  - ncdu
  - moreutils
  - unzip
  - fail2ban
  - bonnie++
  - lm-sensors
  - smartmontools
  - cockpit

# Configure fail2ban
f2b_jail_local: |

      [DEFAULT]

      findtime = 15m

      bantime = 2h

      maxretry = 5



      [sshd]

      enabled = true

      maxretry = 3


