---
pyload_enabled: false
pyload_available_externally: false

# directories
pyload_config_directory: "{{ docker_home }}/pyload"
pyload_download_directory: "{{ downloads_root }}"

# uid / gid
pyload_user_id: "{{ uid }}"
pyload_group_id: "{{ gid }}"

# network
pyload_hostname: "pyload"
pyload_port: "8000"
pyload__ports: 
  - "{{ pyload_port }}:{{ container_pyload_port }}"

# docker
pyload_container_name: "pyload"
pyload_image_name: "writl/pyload"
pyload_image_version: "latest"

# specs
pyload_memory: "1g"
