---
# Sets the hostname of your Ansible NAS
ansible_nas_hostname: ansible-nas

# Update all apt packages when playbook is run
keep_packages_updated: true

# Sets the timezone for your Ansible NAS
# You can find a list here https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
ansible_nas_timezone: Asia/Calcutta

# List of additional APT repositories for all hosts in Ansible inventory.
apt__repositories:
  - name: "docker-ctop"
    uris: "http://packages.azlux.fr/debian"
    signed_by: "https://azlux.fr/repo.gpg.key"
    suites: "stable"
    components: "main"
    enabled: yes