---
organizr_enabled: false
organizr_available_externally: false

# directories
organizr_data_directory: "{{ docker_home }}/organizr"

# network
organizr_port_http: "10081"
organizr_port_https: "10444"
organizr_hostname: "organizr"
organizr__ports: 
  - "{{ organizr_port_http }}:{{ container_organizr_port_http }}"
  - "{{ organizr_port_https }}:{{ container_organizr_port_https }}"

# docker
organizr_container_name: "organizr"
organizr_image_name: "organizr/organizr"
organizr_image_version: "latest"
organizr_user_id: "1000"
organizr_group_id: "1000"

# specs
organizr_memory: 1g
