---
- name: Start Qbittorrent
  block:
    - name: Create Qbittorrent Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        # mode: 0755
      with_items:
        - "{{ qbittorrent_config_directory }}"
        - "{{ qbittorrent_download_directory }}"
        - "{{ qbittorrent_watch_directory }}"

    - name: Qbittorrent Docker Container for external
      community.docker.docker_container:
        name: "{{ qbittorrent_container_name }}"
        image: "{{ qbittorrent_image_name }}:{{ qbittorrent_image_version }}"
        pull: true
        volumes:
          - "{{ qbittorrent_config_directory }}:/config:rw"
          - "{{ qbittorrent_download_directory }}:/downloads:rw"
          - "{{ qbittorrent_watch_directory }}:/watch:rw"
        ports:
          - "{{ qbittorrent_webui_port }}:8080"
          - "{{ qbittorrent_external_port }}:6881"
          - "{{ qbittorrent_external_port }}:6881/udp"
        env:
          TZ: "{{ qbittorrent_timezone }}"
          PUID: "{{ qbittorrent_user_id }}"
          PGID: "{{ qbittorrent_group_id }}"
          WEBUI_PORT: "{{ qbittorrent_webui_port }}"
        restart_policy: unless-stopped
        memory: "{{ qbittorrent_memory }}"
        labels:
          traefik.enable: "{{ qbittorrent_available_externally | string }}"
          traefik.http.routers.qbittorrent.rule: "Host(`{{ qbittorrent_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.qbittorrent.tls.certresolver: "letsencrypt"
          traefik.http.routers.qbittorrent.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.qbittorrent.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.qbittorrent.loadbalancer.server.port: "8080"
      when: qbittorrent_available_externally is true

    - name: Qbittorrent Docker Container
      community.docker.docker_container:
        name: "{{ qbittorrent_container_name }}"
        image: "{{ qbittorrent_image_name }}:{{ qbittorrent_image_version }}"
        pull: true
        volumes:
          - "{{ qbittorrent_config_directory }}:/config:rw"
          - "{{ qbittorrent_download_directory }}:/downloads:rw"
          - "{{ qbittorrent_watch_directory }}:/watch:rw"
        ports:
          - "{{ qbittorrent_webui_port }}:8080"
          - "{{ qbittorrent_external_port }}:6881"
          - "{{ qbittorrent_external_port }}:6881/udp"
        env:
          TZ: "{{ qbittorrent_timezone }}"
          PUID: "{{ qbittorrent_user_id }}"
          PGID: "{{ qbittorrent_group_id }}"
          WEBUI_PORT: "{{ qbittorrent_webui_port }}"
        restart_policy: unless-stopped
        memory: "{{ qbittorrent_memory }}"        
      when: qbittorrent_available_externally is false

  when: qbittorrent_enabled is true

- name: Stop Qbittorrent
  block:
    - name: Stop Qbittorrent
      community.docker.docker_container:
        name: "{{ qbittorrent_container_name }}"
        state: absent
  when: qbittorrent_enabled is false
