---
heimdall_enabled: false
heimdall_available_externally: false

# directories
heimdall_docker_image: linuxserver/heimdall:latest
heimdall_data_directory: "{{ docker_home }}/heimdall"

# network
heimdall_port_http: "10080"
heimdall_port_https: "10443"
heimdall_hostname: heimdall
heimdall__ports: 
  - "{{ heimdall_port_http }}:{{ container_heimdall_port_http }}"
  - "{{ heimdall_port_https }}:{{ container_heimdall_port_https }}"

# uid / gid
heimdall_user_id: "1310"
heimdall_group_id: "1310"

# specs
heimdall_memory: 1g

heimdall_container_name: heimdall
