---
- ansible.builtin.include_tasks: portslist.yml

- name: Start lazytainer
  block:
    - name: Template Docker compose config
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: /tmp/docker-compose.yml
      register: lazytainer_config
  when: lazytainer_enabled is true

- name: Stop lazytainer
  block:
    - name: Stop lazytainer
      community.docker.docker_container:
        name: "{{ lazytainer_container_name }}"
        state: absent
  when: lazytainer_enabled is false
