---
- ansible.builtin.include_tasks: portslist.yml

- name: Start lazytainer
  block:
    - name: Lazytainer Docker Container
      community.docker.docker_container:
        name: "{{ lazytainer_container_name }}"
        image: "{{ lazytainer_image_name }}:{{ lazytainer_image_version }}"
        pull: true
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        ports: "{{ lazytainer_ports }}" 
        env:
          VERBOSE: "true"
        memory: "{{ lazytainer_memory }}"
        labels: "{{ lazytainer_labels }}"

- name: Stop lazytainer
  block:
    - name: Stop lazytainer
      community.docker.docker_container:
        name: "{{ lazytainer_container_name }}"
        state: absent
  when: lazytainer_enabled is false
