---
lazytainer_enabled: false

# docker
lazytainer_container_name: "lazytainer"
lazytainer_image_name: "ghcr.io/vmorganp/lazytainer"
lazytainer_image_version: "master"
lazytainer_container: "container:{{ lazytainer_container_name }}"

# config
lazytainer_inactiveTimeout: "900"
lazytainer_minPacketThreshold: "50"
lazytainer_pollRate: "1"

# specs
lazytainer_memory: "1g"

###########################################################################
###########################################################################

## Lazytainer enabled applications
lazytainer_airsonic_enabled: false
lazytainer_bazarr_enabled: false
lazytainer_booksonic_enabled: false
lazytainer_calibre_enabled: false
lazytainer_cloudcmd_enabled: false
lazytainer_code_server_enabled: false
lazytainer_couchpotato_enabled: false
lazytainer_dashy_enabled: false
lazytainer_deluge_enabled: false
lazytainer_dockge_enabled: false
lazytainer_dokuwiki_enabled: false
lazytainer_duplicacy_enabled: false
lazytainer_duplicati_enabled: false
lazytainer_emby_enabled: false
lazytainer_esphome_enabled: false
lazytainer_freshrss_enabled: false
lazytainer_gotify_enabled: false
lazytainer_guacamole_enabled: false
lazytainer_heimdall_enabled: false
lazytainer_jackett_enabled: false
lazytainer_jellyfin_enabled: false
lazytainer_komga_enabled: false
lazytainer_krusader_enabled: false
lazytainer_lidarr_enabled: false
lazytainer_mealie_enabled: false
lazytainer_mylar_enabled: false
lazytainer_n8n_enabled: false
lazytainer_navidrome_enabled: false
lazytainer_netdata_enabled: false
lazytainer_nzbget_enabled: false
lazytainer_octoprint_enabled: false
lazytainer_ombi_enabled: false
lazytainer_organizr_enabled: false
lazytainer_overseerr_enabled: false
lazytainer_piwigo_enabled: false
lazytainer_portainer_enabled: false
lazytainer_prowlarr_enabled: false
lazytainer_pyload_enabled: false
lazytainer_qbittorrent_enabled: false
lazytainer_radarr_enabled: false
lazytainer_rssbridge_enabled: false
lazytainer_sabnzbd_enabled: false
lazytainer_sickchill_enabled: false
lazytainer_sonarr_enabled: false
lazytainer_tiddlywiki_enabled: false
lazytainer_transmission_enabled: false
lazytainer_ubooquity_enabled: false
lazytainer_unmanic_enabled: false
lazytainer_utorrent_enabled: false
lazytainer_wallabag_enabled: false













