---
lazytainer_enabled: false

# docker
lazytainer_container_name: "lazytainer"
lazytainer_image_name: "ghcr.io/vmorganp/lazytainer"
lazytainer_image_version: "master"
lazytainer_container: "container:{{ lazytainer_container_name }}"

# config
lazytainer_inactiveTimeout: "120"
lazytainer_minPacketThreshold: "100"
lazytainer_pollRate: "1"

# specs
lazytainer_memory: "1g"

# ports
lazytainer_ports: []

###########################################################################
###########################################################################

##
### Jackett
##

lazytainer_jackett_enabled: false

# network
jackett__ports: 
  - "{{ jackett_port }}:{{ container_jackett_port }}"
lazytainer_jackett_port: "{{ jackett__ports if ( lazytainer_jackett_enabled is true ) else [] }}"
lazytainer_ports: "{{ lazytainer_ports + lazytainer_jackett_port }}"

##
### Jellyfin
##

lazytainer_jellyfin_enabled: false

# network
jellyfin__ports_http:
  -  "{{ jellyfin_port_http }}:{{ container_jellyfin_port_http }}"
jellyfin__ports_https:
  - "{{ jellyfin_port_https }}:{{ container_jellyfin_port_https }}"

lazytainer_jellyfin_port_http: "{{ jellyfin__ports_http if ( lazytainer_jellyfin_enabled is true ) else [] }}"
lazytainer_jellyfin_port_https: "{{ jellyfin__ports_https if ( lazytainer_jellyfin_enabled is true ) else [] }}"
lazytainer_ports: "{{ lazytainer_ports + lazytainer_jellyfin_port_http + lazytainer_jellyfin_port_http }}"

###########################################################################
###########################################################################