---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Get lazytainer container state
      community.docker.docker_container:
        name: "{{ lazytainer_container_name }}"
      register: result

    - name: Check if lazytainer containers are running
      ansible.builtin.assert:
        that:
          - result.container['State']['Status'] == "running"
          - result.container['State']['Restarting'] == false
