---
##                       ._____.   .__
##  _____    ____   _____|__\_ |__ |  |   ____             ____ _____    ______
##  \__  \  /    \ /  ___/  || __ \|  | _/ __ \   ______  /    \\__  \  /  ___/
##   / __ \|   |  \\___ \|  || \_\ \  |_\  ___/  /_____/ |   |  \/ __ \_\___ \
##  (____  /___|  /____  >__||___  /____/\___  >         |___|  (____  /____  >
##       \/     \/     \/        \/          \/               \/     \/     \/
##     a n s i b l e - n a s      https://github.com/davestephens/ansible-nas

# Add your all.yml config overrides to this file. See group_vars/all.yml for all possible settings.

# Example options

###
### General
###
ansible_nas_hostname: ansible-nas
ansible_nas_timezone: Asia/Calcutta

# Will be added to the docker group to give user command line access to docker
ansible_nas_user: clearsky

###
### Samba
###
# The location where all shares will be created by default. Can be overridden on a per-share basis.
# This path will be mounted to backup containers, Duplicati
samba_shares_root: /mnt/local/Media

# Where Encoder Cache will be stored
cache_root: /tmp/cache

# Where stuff downloaded will be stored
downloads_root: "{{ samba_shares_root }}/Downloads"

# Where your movies are stored
movies_root: "{{ samba_shares_root }}/Movies"

# Where your TV episodes are stored
tv_root: "{{ samba_shares_root }}/TV"

# Where torrent files are stored (picked up by Transmission for downloading)
torrents_root: "{{ samba_shares_root }}/Torrents"

# Where music is stored
music_root: "{{ samba_shares_root }}/Music"

# Where podcasts are stored
podcasts_root: "{{ samba_shares_root }}/Podcasts"

# Where your books are stored
books_root: "{{ samba_shares_root }}/Books"

# Where your audiobooks are stored
audiobooks_root: "{{ samba_shares_root }}/Audiobooks"

# Where your comics are stored
comics_root: "{{ samba_shares_root }}/Comics"

# Where photos are stored
photos_root: "{{ samba_shares_root }}/Photos"

# Where paperless_ng consumes documents
documents_root: "{{ samba_shares_root }}/Documents"

# Where personal repos and code are stored
code_root: "{{ samba_shares_root }}/Code"

# The description that'll appear next to your Ansible-NAS box when browsing your network
samba_server_string: Ansible NAS

# Shares you want published over Samba.
samba_shares:
  - name: Downloads
    comment: "Stuff downloaded"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ downloads_root }}"

  - name: Movies
    comment: "Movies"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ movies_root }}"

  - name: TV
    comment: "TV Episodes"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ tv_root }}"

  - name: Music
    comment: "Music"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ music_root }}"

  - name: Podcasts
    comment: "Podcasts"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ podcasts_root }}"

  - name: dump
    comment: "File dump"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ samba_shares_root }}/dump"

  - name: Games
    comment: "Games"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ samba_shares_root }}/Games"

  - name: Photos
    comment: "Pictures"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ photos_root }}"

  - name: Books
    comment: "Books"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ books_root }}"

  - name: Audiobooks
    comment: "Audiobooks"
    guest_ok: yes
    public: yes
    writable: yes
    browsable: yes
    path: "{{ audiobooks_root }}"

  - name: Comics
    comment: "Comics"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ comics_root }}"

  - name: Documents
    comment: "Documents"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ documents_root }}"

  - name: Code
    comment: "Code"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ code_root }}"

###
### NFS
###
# Data you want published over NFS. More info on the NFS config format can be found at
# https://help.ubuntu.com/community/SettingUpNFSHowTo#Shares
# WARNING: Weird things might happen if you share the same data over Samba and NFS and allow writes on both!

nfs_shares_root: /mnt/local/Media

nfs_exports:
  - "{{ nfs_shares_root }}/public *(rw,sync,no_root_squash)"

###
### Samba
###
# Seems to break browsing of the \\server-name shares root when enabled
samba_mitigate_cve_2017_7494: false

# Enable apple exentensions for compatibility with apple clients
samba_apple_extensions: yes

# The account used when Samba shares are accessed. Shouldn't need to change this unless you want to
# mess with Samba user permissions.
samba_guest_account: ansible-nas

# How Samba behaves when an unknown user connects, see Samba docs for more info
samba_map_to_guest: Bad Password

# The NetBIOS hostname used by Samba on your network
samba_netbios_name: "{{ ansible_nas_hostname }}"

## Enable some applications
portainer_enabled: false
lazytainer_enabled: true
jellyfin_enabled: true
jackett_enabled: true

## Applications controlled by Lazytainer
lazytainer_jackett_enabled: true
lazytainer_jellyfin_enabled: true



## Firewall Settings

# Whether to flush all rules and chains whenever the firewall is restarted. Set this to false if there are other processes managing iptables (e.g. Docker).
firewall_flush_rules_and_chains: false

# A list of TCP or UDP ports (respectively) to open to incoming traffic.
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "9090" # Cockpit
  - "9117" # Jackett
  - "8896" # Jellyfin HTTP
  - "8928" # Jellyfin HTTPS
firewall_allowed_udp_ports: []


