---
gotify_enabled: false
gotify_available_externally: false

# data directory
gotify_data_directory: "{{ docker_home }}/gotify"

# network
gotify_port: "2346"
gotify_hostname: "gotify"

# docker
gotify_container_name: "gotify"
gotify_image_name: "gotify/server"
gotify_image_version: "latest"
gotify_user_id: "{{ uid }}"
gotify_group_id: "{{ gid }}"

# specs
gotify_memory: 200m
